//
// ExceptionModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ExceptionModel: Codable {

    public var errorCode: String?
    public var errorMessage: String?
    public var additionalInformation: Any?

    public init(errorCode: String? = nil, errorMessage: String? = nil, additionalInformation: Any? = nil) {
        self.errorCode = errorCode
        self.errorMessage = errorMessage
        self.additionalInformation = additionalInformation
    }

}
