//
// AttachmentDetailModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AttachmentDetailModel: Codable {

    public var exists: Bool?
    public var downloadUrl: String?
    public var downloadUrlValidTill: Date?
    public var uploadUrl: String?
    public var uploadUrlValidTill: Date?

    public init(exists: Bool? = nil, downloadUrl: String? = nil, downloadUrlValidTill: Date? = nil, uploadUrl: String? = nil, uploadUrlValidTill: Date? = nil) {
        self.exists = exists
        self.downloadUrl = downloadUrl
        self.downloadUrlValidTill = downloadUrlValidTill
        self.uploadUrl = uploadUrl
        self.uploadUrlValidTill = uploadUrlValidTill
    }

}
