//
// BackerPaymentRequestModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BackerPaymentRequestModel: Codable {

    public var checkoutUrl: String?

    public init(checkoutUrl: String? = nil) {
        self.checkoutUrl = checkoutUrl
    }

}
