//
// BackerDetailModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BackerDetailModel: Codable {

    public var id: String?
    public var name: String?
    public var emailAddress: String?

    public init(id: String? = nil, name: String? = nil, emailAddress: String? = nil) {
        self.id = id
        self.name = name
        self.emailAddress = emailAddress
    }

}
