//
// CheckoutBackerCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CheckoutBackerCommand: Codable {

    public var totalAmount: Double?
    public var currency: String?
    public var description: String?
    public var redirectUrl: String?

    public init(totalAmount: Double? = nil, currency: String? = nil, description: String? = nil, redirectUrl: String? = nil) {
        self.totalAmount = totalAmount
        self.currency = currency
        self.description = description
        self.redirectUrl = redirectUrl
    }

}
