//
// EventTargetDetailModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EventTargetDetailModel: Codable {

    public var type: EventTargetType?
    public var value: String?

    public init(type: EventTargetType? = nil, value: String? = nil) {
        self.type = type
        self.value = value
    }

}
