//
// FinishParticipantCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FinishParticipantCommand: Codable {

    public var distanceInMeters: Double?

    public init(distanceInMeters: Double? = nil) {
        self.distanceInMeters = distanceInMeters
    }

}
