//
// ParticipantListModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ParticipantListModel: Codable {

    public var id: String?
    public var name: String?
    public var eventId: String?

    public init(id: String? = nil, name: String? = nil, eventId: String? = nil) {
        self.id = id
        self.name = name
        self.eventId = eventId
    }

}
