//
// ParticipantGoalType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 0 &#x3D; DonationAmount 1 &#x3D; Distance 2 &#x3D; Time */
public enum ParticipantGoalType: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
