//
// ParticipantGoalDetailModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ParticipantGoalDetailModel: Codable {

    public var type: ParticipantGoalType?
    public var value: String?

    public init(type: ParticipantGoalType? = nil, value: String? = nil) {
        self.type = type
        self.value = value
    }

}
