//
// RegisterParticipantCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterParticipantCommand: Codable {

    public var name: String?
    public var targets: [RegisterEventTargetCommand]?

    public init(name: String? = nil, targets: [RegisterEventTargetCommand]? = nil) {
        self.name = name
        self.targets = targets
    }

}
