//
// RegisterParticipantCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterParticipantCommand: Codable {

    public var name: String?

    public init(name: String? = nil) {
        self.name = name
    }

}
