//
// ValidationExceptionError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ValidationExceptionError: Codable {

    public var property: String?
    public var errorMessage: String?

    public init(property: String? = nil, errorMessage: String? = nil) {
        self.property = property
        self.errorMessage = errorMessage
    }

}
