//
// ParticipantsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ParticipantsAPI {
    /**
     GetParticipantDetail
     
     - parameter eventId: (path)  
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func participantsGet(eventId: String, id: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ParticipantDetailModel?, _ error: Error?) -> Void)) {
        participantsGetWithRequestBuilder(eventId: eventId, id: id).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     GetParticipantDetail
     - GET /events/{eventId}/participants/{id}
     - Returns the detail of a participant for a given event
     - parameter eventId: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<ParticipantDetailModel> 
     */
    open class func participantsGetWithRequestBuilder(eventId: String, id: String) -> RequestBuilder<ParticipantDetailModel> {
        var path = "/events/{eventId}/participants/{id}"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ParticipantDetailModel>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     GetParticipantsList
     
     - parameter eventId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func participantsGetAll(eventId: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [ParticipantListModel]?, _ error: Error?) -> Void)) {
        participantsGetAllWithRequestBuilder(eventId: eventId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     GetParticipantsList
     - GET /events/{eventId}/participants
     - Returns a list of participants for a given event
     - parameter eventId: (path)  
     - returns: RequestBuilder<[ParticipantListModel]> 
     */
    open class func participantsGetAllWithRequestBuilder(eventId: String) -> RequestBuilder<[ParticipantListModel]> {
        var path = "/events/{eventId}/participants"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[ParticipantListModel]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     RegisterParticipant
     
     - parameter eventId: (path)  
     - parameter registerParticipantCommand: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func participantsPost(eventId: String, registerParticipantCommand: RegisterParticipantCommand, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ParticipantDetailModel?, _ error: Error?) -> Void)) {
        participantsPostWithRequestBuilder(eventId: eventId, registerParticipantCommand: registerParticipantCommand).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     RegisterParticipant
     - POST /events/{eventId}/participants
     - Registers a participant for a given event
     - parameter eventId: (path)  
     - parameter registerParticipantCommand: (body)  
     - returns: RequestBuilder<ParticipantDetailModel> 
     */
    open class func participantsPostWithRequestBuilder(eventId: String, registerParticipantCommand: RegisterParticipantCommand) -> RequestBuilder<ParticipantDetailModel> {
        var path = "/events/{eventId}/participants"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registerParticipantCommand)

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ParticipantDetailModel>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
