//
// EventDetailModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EventDetailModel: Codable {

    public var id: Int64?
    public var name: String?
    public var startDate: Date?
    public var endDate: Date?
    public var city: String?
    public var address: String?
    public var comment: String?

    public init(id: Int64? = nil, name: String? = nil, startDate: Date? = nil, endDate: Date? = nil, city: String? = nil, address: String? = nil, comment: String? = nil) {
        self.id = id
        self.name = name
        self.startDate = startDate
        self.endDate = endDate
        self.city = city
        self.address = address
        self.comment = comment
    }

}
